
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/gauthiercorion/Desktop/blokusoffgame/blokus-amazing/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    279.0,
    883.0,
    image=image_image_2
)

canvas.create_text(
    157.639892578125,
    840.0,
    anchor="nw",
    text="PERSONNE 3",
    fill="#FFFFFF",
    font=("LilitaOne", 48 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    719.0,
    464.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    717.0,
    577.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1156.0,
    883.0,
    image=image_image_5
)

canvas.create_text(
    1034.639892578125,
    840.0,
    anchor="nw",
    text="PERSONNE 4",
    fill="#FFFFFF",
    font=("LilitaOne", 48 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1266.0,
    683.04345703125,
    image=image_image_6
)

canvas.create_text(
    1194.0,
    657.04345703125,
    anchor="nw",
    text="FACILE",
    fill="#FFFFFF",
    font=("LilitaOne", 32 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    1266.91796875,
    622.521728515625,
    image=image_image_7
)

canvas.create_text(
    1194.91796875,
    596.521728515625,
    anchor="nw",
    text="MOYEN",
    fill="#FFFFFF",
    font=("LilitaOne", 32 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    1266.0,
    562.0,
    image=image_image_8
)

canvas.create_text(
    1194.0,
    536.0,
    anchor="nw",
    text="EXPERT",
    fill="#FFFFFF",
    font=("LilitaOne", 32 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    1156.0,
    147.0,
    image=image_image_9
)

canvas.create_text(
    1034.639892578125,
    104.0,
    anchor="nw",
    text="PERSONNE 2",
    fill="#FFFFFF",
    font=("LilitaOne", 48 * -1)
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    279.0,
    147.0,
    image=image_image_10
)

canvas.create_text(
    157.639892578125,
    104.0,
    anchor="nw",
    text="PERSONNE 1",
    fill="#FFFFFF",
    font=("LilitaOne", 48 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    139.0,
    256.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    1295.0,
    256.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    1185.0,
    775.0,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    1185.0,
    256.0,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    249.0,
    256.0,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    249.0,
    775.0,
    image=image_image_16
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    139.0,
    775.0,
    image=image_image_17
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    1295.0,
    775.0,
    image=image_image_18
)
window.resizable(False, False)
window.mainloop()
