from Pieces import Pieces
import numpy as np

# Constante qui est un dictionnaire comportant l'ensemble des 21 pièces du jeu blokus 
LISTEPIECES : dict[str,Pieces] = {
    "1" : Pieces(np.array([[1]]),1),
    "2" : Pieces(np.array([[1,1]]),2),
    "3" : Pieces(np.array([[1,1,1]]),3),
    "4" : Pieces(np.array([[1,1,1,1]]),4),
    "5" : Pieces(np.array([[1,1,1,1,1]]),5),
    "6" : Pieces(np.array([[1,1],
                           [1,1]]),6),
    "7" :Pieces(np.array([[1,1],
                          [1,0]]),7),
    "8" :Pieces(np.array([[1,1,1],
                          [1,0,0]]),8),
    "9" :Pieces(np.array([[1,1,1],
                          [1,0,0],
                          [1,0,0]]),9),
    "10" : Pieces(np.array([[1,0],
                            [1,1],
                            [1,1]]),10),
    "11" : Pieces(np.array([[1,0],
                            [1,1],
                            [1,0]]),11),
    "12" : Pieces(np.array([[1,1],
                            [0,1],
                            [1,1]]),12),
    "13" : Pieces(np.array([[1,1,1,1],
                            [0,1,0,0]]),13),
    "14" : Pieces(np.array([[0,1,1,1],
                            [1,1,0,0]]),14),
    "15" : Pieces(np.array([[1,1,1,1],
                            [1,0,0,0]]),15),
    "16" : Pieces(np.array([[0,1,0],
                            [1,1,1],
                            [0,1,0]]),16),
    "17" : Pieces(np.array([[0,1,1],
                            [0,1,0],
                            [1,1,0]]),17),
    "18" : Pieces(np.array([[0,1,0],
                            [0,1,0],
                            [1,1,1]]),18),
    "19" : Pieces(np.array([[1,0,0],
                            [1,1,0],
                            [0,1,1]]),19),
    "20" : Pieces(np.array([[1,1,0],
                            [0,1,1],
                            [0,1,0]]),20),
    "21" : Pieces(np.array([[1,0],
                                  [1,1],
                                  [0,1]]),21),
}
